# Generated by Django 3.0.5 on 2020-07-08 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.CharField(blank=True, max_length=50)),
                ('class2', models.CharField(blank=True, max_length=50)),
                ('class3', models.CharField(blank=True, max_length=50)),
                ('class4', models.CharField(blank=True, max_length=50)),
                ('class5', models.CharField(blank=True, max_length=50)),
                ('class6', models.CharField(blank=True, max_length=50)),
                ('class7', models.CharField(blank=True, max_length=50)),
                ('class8', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
