# Generated by Django 3.0.5 on 2020-10-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20201004_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='productive_time',
            field=models.CharField(choices=[('EB', 'Early_Bird'), ('MM', 'Morning_Magpie'), ('MD', 'Mid_Day_Macaw'), ('AA', 'Afternoon_Albatross'), ('EE', 'Evening_Eagle'), ('NN', 'Nocturnal_Nightingale')], default='AA', max_length=2),
        ),
    ]
