# Generated by Django 3.0.5 on 2020-10-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20201004_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('HW', 'Homework'), ('QZ', 'Quiz'), ('EX', 'Exam')], default='HW', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='productive_time',
            field=models.CharField(choices=[('EB', 'Early Bird: 5am - 8am'), ('MM', 'Morning_Magpie: 8am - 11am'), ('MD', 'Mid_Day_Macaw: 11am - 2pm'), ('AA', 'Afternoon_Albatross: 2pm - 5pm'), ('EE', 'Evening_Eagle: 5pm - 8pm'), ('NO', 'Night Owl: 8pm - 10pm'), ('NN', 'Nocturnal_Nightingale: 11pm - 2am')], default='AA', max_length=2),
        ),
    ]
