# Generated by Django 3.0.5 on 2020-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20201007_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='time_to_complete_estimate',
            field=models.FloatField(default=1.0),
        ),
    ]
