# Generated by Django 3.0.5 on 2020-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_profile_timezone_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone_offset',
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='US/Eastern', max_length=50),
        ),
    ]
