# Generated by Django 3.0.5 on 2020-10-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20201010_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='EST', max_length=50),
        ),
    ]
