# Generated by Django 3.0.5 on 2020-11-01 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0012_auto_20201012_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='productive_time',
            field=models.CharField(choices=[('EB', 'Early Bird: 5am - 8am'), ('MM', 'Morning_Magpie: 8am - 11am'), ('MD', 'Mid_Day_Macaw: 11am - 2pm'), ('AA', 'Afternoon_Albatross: 2pm - 5pm'), ('EE', 'Evening_Eagle: 5pm - 8pm'), ('NO', 'Night Owl: 8pm - 10pm'), ('NN', 'Nocturnal_Nightingale: 10pm - 12pm')], default='AA', max_length=2),
        ),
        migrations.CreateModel(
            name='Scheduled_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HW', 'Homework'), ('QZ', 'Quiz'), ('EX', 'Exam')], default='HW', max_length=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_name', models.CharField(blank=True, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
